WIP: Dsy791/auto reauthenticate expired client
sypht-team/sypht-python-client pull request #16
Opened 2020-08-25 07:36 UTC by wilmeryan

Added access_token expiry check in _get_headers() which already gets called before each request.

2020-08-25 08:10 UTC, andychisholm requested changes

2020-08-25 08:10 UTC, andychisholm commented on sypht/client.py
> +        self._access_token, expires_in = self._authenticate_client()
Suggest consolidating this state management into `self._authenticate()`, then you avoid the similar operation repeated down in `_get_headers` too.

2020-08-26 03:38 UTC, andychisholm approved these changes

2020-08-26 03:49 UTC, anaoum approved these changes

2020-08-26 03:49 UTC, merged