Black formatting, header params, verbose results
sypht-team/sypht-python-client pull request #17
Opened 2020-09-09 10:59 UTC by andychisholm

2020-09-09 11:00 UTC, andychisholm commented
Functional commits are:
https://github.com/sypht-team/sypht-python-client/pull/17/commits/fcbb18c8829880d7dd8c76e0787b59de356cdc80

and:
https://github.com/sypht-team/sypht-python-client/pull/17/commits/8a7e23e811c06ebe20332140dcc5b9cd0c35196f

2020-09-09 11:06 UTC, anaoum requested changes

2020-09-09 11:06 UTC, anaoum commented on sypht/client.py
> +            endpoint += "&verbose=true"
should be ? not &

2020-09-10 00:36 UTC, anaoum approved these changes

2020-09-10 00:36 UTC, merged